global:
  scrape_interval:     5s
  evaluation_interval: 105s

rule_files:
  - /prometheus/rules/*.rules

scrape_configs:
  - job_name: "gpu"
    static_configs:
      - targets: ['192.168.11.124:9835']
        labels:
            instance: 3080-quad

