{
 "title": "Multi_GPU",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Sum_Power_Watts　合計電圧 [W]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nvidia_smi_power_draw_watts)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory_realtime 使用中メモリ [MiB]",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(nvidia_smi_memory_used_bytes) / 1024 / 1024  >100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average_Power_Used　平均電量使用量",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_smi_power_draw_average_watts",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Temperture 温度 [℃]",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nvidia_smi_temperature_gpu", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Utilization 利用率",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu_ratio>0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number_of_failed_connections 接続失敗回数",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "nvidia_smi_failed_scrapes_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Alert for temperature",
   "type": "timeseries",
   "description": "Don`t delete this grah.This is linking with the alert.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "targets": [
    { "expr": "nvidia_smi_temperature_gpu>50", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Sum_Memory 合計メモリ [GiB]",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nvidia_smi_memory_used_bytes) / 1024 / 1024 /1024",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}